import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import Search from './ui/search'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className=' h-14 mb-12'>
          <ul className='flex flex-row gap-14 justify-end pr-20 h-full items-center'>
            <Link href={'/'}>Incio</Link>
            <Link href={'./popular'}>Populares</Link>
            <Link href={'./'}>Generos</Link>
          </ul>
        </nav>
        <div >
          <Search></Search>
        </div>
        {children}
        </body>
    </html>
  )
}
